#!/usr/bin/env bash
mkdir -p dist
echo "build src/server.ls -> dist/server.js ..."
./node_modules/.bin/lsc -cbp src/server.ls > dist/server.js
echo "build src/client.ls -> dist/wrapper.js ..."
./node_modules/.bin/lsc -cbp src/client.ls > dist/wrapper.js
echo "bundling disst/wrapper.js for browser ... "
./node_modules/.bin/browserify dist/wrapper.js -o dist/wrapper.js
echo "build src/ot-diff.ls -> dist/ot-diff.js ..."
./node_modules/.bin/lsc -cbp src/ot-diff.ls > dist/ot-diff.js
echo "bundling src/ot-diff.js for browser ... "
./node_modules/.bin/browserify dist/ot-diff.js -o dist/ot-diff.js
# TODO need transpile before we could uglify
#echo "minifying sharedb-wrapper.js ..."
#./node_modules/.bin/uglifyjs dist/wrapper.js > dist/wrapper.min.js
echo "deploy wrapper.js to web/ ..."
mkdir -p web/static/assets/lib/sharedb/
cp dist/wrapper.js web/static/assets/lib/sharedb/
echo "done."

