#!/usr/bin/env bash
mkdir -p dist
echo "build src/server.ls -> dist/server.js ..."
./node_modules/.bin/lsc -cbp src/server.ls > dist/server.js
echo "build src/client.ls -> dist/wrapper.js ..."
./node_modules/.bin/lsc -cbp src/client.ls > dist/wrapper.js
echo "build src/ot-diff.ls -> dist/ot-diff.js ..."
./node_modules/.bin/lsc -cbp src/ot-diff.ls > dist/ot-diff.js
echo "bundling src/ot-diff.ls for browser ... "
./node_modules/.bin/browserify dist/ot-diff.js -o dist/ot-diff.js
echo "minifying sharedb-wrapper.js ..."
./node_modules/.bin/uglifyjs dist/wrapper.js > dist/wrapper.min.js
# TODO need transpile ot-diff before we could uglify it with client.
echo "merge ot-diff and wrapper..."
cat dist/ot-diff.js >> dist/wrapper.js
cat dist/ot-diff.js >> dist/wrapper.min.js
echo "deploy wrapper.js to web/ ..."
mkdir -p web/static/assets/lib/sharedb/
cp dist/wrapper.min.js web/static/assets/lib/sharedb/
cp dist/wrapper.js web/static/assets/lib/sharedb/
echo "done."

